#!/usr/bin/env python
from getpass import getpass
from fabric.api import *
import sys
import os
#@env.gateway = 'username@IPofgatewayHost'


env.password = getpass('Enter the password for: ')
env.sudo_password = env.password
list = []

print(file)
# file function needs to be added before execution any other tasks for multiple host list in file hosts
# how to use this script: fab -f fab_ipmon_dev.py file:name=hosts ipmon_status
def file(**kwargs):
        for key, value in kwargs.iteritems():
                hosts = value
        with open(hosts, "r") as file:
                for line in file:
                        list.append(line)
                env.hosts = list;
                
def log(msg):
        logfile=open("error.list", "a+")
        logfile.write(msg + "\n")
        logfile.close()

def ipmon_restart():
        sudo("/etc/init.d/IPmonX restart")
        
def ipmonx_restart():
        sudo("/etc/init.d/IPmonX restart")

def ipmon_status():
        sudo('sudo /etc/init.d/IPmon status')

def ipmon_disk():
        #env.user = 'user'
        #env.password = 'password'      
        sudo("find /apps/IPsoft/IPmon/var -type f -not -name '*.gz' -name '*log*' -name '*201*' -exec gzip -9v {} \;")
        sudo("find /apps/IPsoft/IPmon/var -type f -not -name '*.gz' -name '*service-perfdata*201*' -exec gzip -9v {} \;")
        sudo("find /apps/IPsoft/IPmon/engine/jmx/log/jmx1.2/ -type f -not -name '*.gz' -name 'engine.log.201*' -exec gzip -9v {} \;")

def cp_ntp():
  with settings(warn_only=True):
        try:
          sudo("/etc/init.d/puppet stop")
          sudo("cp -p /etc/ntp.conf /root/")
          put('./ntp.conf', '/etc/ntp.conf', mode=0644, use_sudo=True)
          sudo("chown root:root /etc/ntp.conf")
          sudo("/etc/init.d/ntpd restart")
          sudo("chkconfig puppet off")
          sudo("sed  -i '/puppet/d' /var/spool/cron/root")
          sudo("mv /etc/init.d/puppet /etc/init.d/puppet.old")
        except Exception, e:
          log('bad host %s::%s'%(env.host,str(e)))


def ntp():
  with settings(warn_only=True):
        try:
          sudo("/etc/init.d/ntpd stop && ntpdate -d  ntp.svc.ipsoft.com && /etc/init.d/ntpd start")
        except Exception, e:
          log('bad host %s::%s'%(env.host,str(e)))
        
        
